### ISSUE TITLE
Tokenomics Design

### ISSUE THREAD

**Issue by duelingbenjos** [XianChain/xian#10]

**Comment by Endogen** [comment]
Tokenomics Proposal

Purpose | Amount
-- | --
Private Sale | 10%
Public Sale | 20%
Advisors | 5%
Team 5 year release | 25%
Team Upfront | 5%
Airdrops | 5%
Bounties / DAO | 30%

![Image](https://github.com/XianChain/xian/assets/226475/5a0d54ed-d310-4d99-bfa6-3f476989e08d)
