### ISSUE TITLE
Can we still have FIFO?

### ISSUE THREAD

**Issue by duelingbenjos** [XianChain/xian#6]
> That said, if the transactions contain some internal value, like an order/nonce/sequence number, the application can reject transactions that are out of order. So if a node receives tx3, then tx1, it can reject tx3 and then accept tx1. The sender can then retry sending tx3, which should probably be rejected until the node has seen tx2.

https://docs.cometbft.com/v0.38/core/mempool

**Comment by crosschainer** [comment]
just add timestamp to tx  and work on it in order
